version: '3'
services:
  postgresql:
    container_name: postgresql-prod
    image: postgres:13-alpine
    # cpus: 1
    # cpu_count: 1
    # mem_limit: 2g
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=lmao
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/db
    networks:
      - vape-service

  flyway:
    container_name: flyway
    image: flyway/flyway
    mem_limit: 256mb
    # cpus: 0.3
    # cpu_count: 1
    depends_on:
      - postgresql
    volumes:
      - './sql:/flyway/sql'
    command: -url=jdbc:postgresql://postgresql:5432/postgres -user="user" -password="password" -mixed="true" -connectRetries=60 migrate
    networks:
      - vape-service

  vapestore_backend:
    container_name: vapestore_backend_prod
    image: x2pher69/vapestore_backend:latest
    # cpus: 2
    # cpu_count: 1
    # mem_limit: 2g
    command: sh -c "yarn install && yarn start:dev"
    environment:
      NODE_ENV: development
      PORT: 4000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgresql
    ports:
      - '4000:4000'
    networks:
      - vape-network
      - vape-service

networks:
  vape-service:
    name: vape-service
    external: false
  vape-network:
    name: vape-network
    driver: bridge
