version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=lmao
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/db
    networks:
      - vape-service

  flyway:
    container_name: flyway
    image: flyway/flyway
    mem_limit: 256mb
    depends_on:
      - postgresql
    volumes:
      - './sql:/flyway/sql'
    command: -url=jdbc:postgresql://postgresql:5432/postgres -user="user" -password="password" -mixed="true" -connectRetries=60 migrate
    networks:
      - vape-services

networks:
  vape-service:
    name: vape-service
    external: false
